title: Priceless Pricing
description: A minimalistic pricing strategy reference site
theme: just-the-docs

url: https://jtbowlin.github.io/pricelesspricing/

aux_links:
  About the Author: https://www.linkedin.com/in/jtbowlin/
